name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '3.0' ]

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        version: ${{ matrix.ruby }}
    - name: Build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        chmod 600 ./spec/fixtures/*
        bundle exec rspec
